version: "3.7"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 6432:5432
    expose:
      - 5432
    shm_size: 1gb
    networks:
      - backendnet
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend123
      - POSTGRES_DB=backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U backend -d backend" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backendnet:
    name: backend_network